data_dir: /home/siavash/random/dssegsecond/data
processed_dir: /home/siavash/random/dssegsecond/processed_data
output_dir: /home/siavash/random/dssegsecond/output
model_dir: /home/siavash/random/dssegsecond/output/train
sub_dir: ./