# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: inference
    chdir: true
  run:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}/single
  sweep:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}
    subdir: run${hydra.job.num}

defaults:
  - _self_
  - dir: local
  - model: Spec2DCNN
  - feature_extractor: WaveNetSpectrogram #LSTMFeatureExtractor #
  - decoder: UNet1DDecoderLSTM #UNet1DDecoder #TransformerDecoder

exp_name: dummy
phase: test
n_folds: 5
weight:
  exp_name: ${exp_name}
  run_name: single
  file_name: best_model.pth
model_path_list:
  - "/kaggle/input/cmi-model-14/expfeatd10/runf0/best_model.pth"
  - "/kaggle/input/cmi-model-14/expfeatd10/runf1/best_model.pth"
  - "/kaggle/input/cmi-model-14/expfeatd10/runf2/best_model.pth"
  - "/kaggle/input/cmi-model-14/expfeatd10/runf7/best_model.pth"
  - "/kaggle/input/cmi-model-14/expfeatd10/runf8/best_model.pth"
  - "/kaggle/input/cmi-model-14/expfeatd10/runf9/best_model.pth"
  - "/kaggle/input/cmi-model-14x/exp_f1t/runf3/best_model.pth"
  - "/kaggle/input/cmi-model-14x/exp_f1t/runf10/best_model.pth"

seed: 42
duration: 17280 
downsample_rate: 2 
upsample_rate: 1
batch_size: 32
num_workers: 2
use_amp: true
average_type: "mean"

# augmentation
augmentation:
  mixup_prob: 0.0
  mixup_alpha: 0.4
  cutmix_prob: 0.0
  cutmix_alpha: 0.4

# post_process
post_process:
  score_th: 0.02
  distance: 10

# label
labels:
  - "awake"
  - "event_onset"
  - "event_wakeup"

# feature
features:
  # - "minute"
  # - "anglez_original"
  - "anglez"
  - "minute"
  - "anglez_sin"
  - "anglez_cos"
  - "enmo"
  - "hour_sin"
  - "hour_cos"
  - "anglez_diff_rolling_med_65"
  - "anglez_diff_rolling_mean_65"
  - "anglez_diff_rolling_max_65"
  - "anglez_diff_rolling_std_65"
  - "enmo_diff_rolling_med_65"
  - "enmo_diff_rolling_mean_65"
  - "enmo_diff_rolling_max_65"
  - "enmo_diff_rolling_std_65"
  - "anglez_diff_rolling_med_33"
  - "anglez_diff_rolling_mean_33"
  - "anglez_diff_rolling_max_33"
  - "anglez_diff_rolling_std_33"
  - "enmo_diff_rolling_med_33"
  - "enmo_diff_rolling_mean_33"
  - "enmo_diff_rolling_max_33"
  - "enmo_diff_rolling_std_33"
  # - "anglez_diff_rolling_med_17"
  # - "anglez_diff_rolling_mean_17"
  # - "anglez_diff_rolling_max_17"
  # - "anglez_diff_rolling_std_17"
  # - "enmo_diff_rolling_med_17"
  # - "enmo_diff_rolling_mean_17"
  # - "enmo_diff_rolling_max_17"
  # - "enmo_diff_rolling_std_17"
  - "anglez_diff_1"
  - "anglez_diff_2"
  - "anglez_diff_4"
  - "anglez_diff_8"
  - "anglez_diff_16"
  - "enmo_diff_1"
  - "enmo_diff_2"
  - "enmo_diff_4"
  - "enmo_diff_8"
  - "enmo_diff_16"
